### ISSUE TITLE
Require locally?

### ISSUE THREAD

**Issue by marvindanig** [mattdesl/ghrepo#11]
This isn't an issue per se, [ghrepo](https://github.com/mattdesl/ghrepo) works perfectly well on my machine and it is awesome. Thanks for this great package! But here's something that I want to do via a submodule:

Submodule's `package.json` has:

```
"dependencies": {
    …
    "executive": "1.1.7",
    "ghrepo": "1.3.2"
  }
```

```
const checker = require('ghrepo');
const exec = require('executive');

module.exports = {
    setup(message) {
        // exec("git init --quiet && git add . -A && git commit -am 'First commit: new manuscript' --quiet");
        exec("ghrepo -m `First commit ${message}`");
    }
    … other methods.
};

```

At the moment it works with a local require too, but with the following warning/child_process error:

```
Error: ENOENT, spawn ghrepo
Make sure 'ghrepo' exists and is executable.
Preparing project… Done.
? Publish new repo as marvindanig/testproject? Y/n

```

How should I go about tweaking the fork so that global installation of the CLI isn't required and `ghrepo` commands (or a subset) could be programmatically called from inside another node#shellscript?

**Comment by mattdesl** [comment]
Yeah, sadly this is just a CLI-facing module and I currently have no intention of turning it into a programmatic API. Sorry about that! :smile:

**Comment by mattdesl** [comment]
Also, I think you could install ghrepo as a local dependency and use this module to spawn/fork/whatever it without needing the user to install it manually:
https://www.npmjs.com/package/npm-execspawn
